# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: actions-setup-mysql
      uses: shogo82148/actions-setup-mysql@v1.2.2
      with:
        mysql-version: '5.7'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
    - run: curl https://raw.githubusercontent.com/xgenecloud/xc-data/master/sakila-data.sql > sakila-data.sql
    - run: curl https://raw.githubusercontent.com/xgenecloud/xc-data/master/sakila-schema.sql > sakila-schema.sql
    - run: mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS sakila;'
    - run: mysql -uroot -h127.0.0.1 --default-character-set=utf8 sakila < sakila-schema.sql
    - run: mysql -uroot -h127.0.0.1 --default-character-set=utf8 sakila < sakila-data.sql

